### ISSUE TITLE
IBANs with any number of special characters mixed in are valid

### ISSUE THREAD

**Issue by zetamorph** [Simplify/ibantools#6] opened 2018-01-02 22:02 UTC
Hi,

I experienced the behaviour described below today.
Is the validity of any number of special characters inside the IBAN intentional?

According to the standard at least, IBANs only consist of alphanumeric characters.

### Expected behavior

```
const IBAN = 'DE2710077777äöüäü###########0209299700'; 
// original: 'DE27100777770209299700'
console.log(ibantools.isValidIBAN(IBAN)); // expect false
```

### Actual behavior

```
const IBAN = 'DE2710077777äöüäü###########0209299700'; 
console.log(ibantools.isValidIBAN(IBAN)); // logs true
```

It´s possible to just remove the special characters with the `ibantools.friendlyFormatIBAN` method, so it´s not a big issue, just something that had me wondering a little.

Best Wishes,
- Johannes

**Comment by Simplify** [comment] 2018-02-13 10:46
Hi @zetamorph,

I just released version 1.6.0 that fixes this issue. Thank you for bug report and sorry about response delay :) 👍

**Comment by basvis** [comment] 2018-02-20 14:32
@Simplify Most special characters are now fixed, but the "-" character is still marked as valid.
So reproduce scenario: "NL85ABNA0246986056----" is accepted as valid IBAN

**Comment by Simplify** [comment] 2018-02-20 14:43
Ok, I see. In `isValidIBAN` i convert IBAN to electronic format first by removing `-` and ` ` chars and making whole thing upper case before doing validation. I guess that should be changed. I'll make new release in next 24 hours. Thanks for reporting this 👍

**Comment by Simplify** [comment] 2018-03-11 20:25
@basvis Issue is [fixed now](https://github.com/Simplify/ibantools/blob/master/ChangeLog). Sorry about delay.

Previously `isValidIBAN` accepted also IBAN's in friendly formats like `NL85 ABNA 0246 9860 56` or `NL85-ABNA-0246-9860-56`. That is no longer the case. Because this is breaking change, version is now 2.0.0.

**Closed by Simplify** 2018-03-11 20:25 UTC
Labels: bug
